{% set name = "napari-ome-zarr" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3d3054823c2adaa4d2bf370c46adcc4a54192cfec3bbbe98d144e50b95bd6f89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python >3.10
    - setuptools-scm
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - ome-zarr >=0.10.3
    - python >3.10
    - vispy

test:
  imports:
    - napari_ome_zarr
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python >3.10

about:
  home: https://github.com/ome/napari-ome-zarr
  summary: A reader for zarr backed OME-NGFF images.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jburel
    - goanpeca
    - jaimergp
    - joshmoore
    - will-moore
