{% set name = "napari-ome-zarr" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6ccf7f0ca31d0199094d2df93f521168d43edf8126387baa53a9365da529fd95

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >3.10
    - setuptools-scm
  run:
    - napari >=0.4.0
    - napari-plugin-engine >=0.1.4
    - numpy
    - ome-zarr >=0.13.0
    - python >3.10
    - vispy

test:
  imports:
    - napari_ome_zarr
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python >3.10

about:
  home: https://github.com/ome/napari-ome-zarr
  summary: A reader for zarr backed OME-NGFF images.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jburel
    - goanpeca
    - jaimergp
    - joshmoore
    - will-moore
