{% set name = "napari-ome-zarr" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-ome-zarr-{{ version }}.tar.gz
  sha256: b889a8901efeafe728cb7aea5231fd14017746d8633add3032a6f5e30289287e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - napari-plugin-engine >=0.1.4
    - numpy
    - ome-zarr >=0.2.0
    - python >=3.7
    - vispy

test:
  imports:
    - napari_ome_zarr
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ome/napari-ome-zarr
  summary: A reader for zarr backed OME-NGFF images.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jburel
    - goanpeca
    - jaimergp
    - joshmoore
    - sbesson
    - will-moore
